#!/usr/bin/env python3
"""Assemble the 4 per-สังคหะ p7 fragments into data/p7.yaml.

    python3 scripts/assemble_p7.py

data/p7/<sangaha>.yaml  one hand-verified fragment per สังคหะ (the สังคหะ dict:
                        id, thai, optional gatha/source/note, sets[]). Each was
                        built by one subagent against
                        reference/02-ปริจเฉทที่7-สมุจจยสังคหะ.md, one สังคหะ per
                        agent (2026-08-30); the per-set verification record is in
                        docs/p7-verification/<sangaha>.md.

This just concatenates them in SANGAHA_ORDER under `sangahas:` and re-stamps the
header comment. data/p7.yaml is generated -- never hand-edit it; edit the
fragment + re-run. scripts/build_data.py then checks every `ongkhatham` id
against data/paramattha.yaml and every `expect` == len(members).
"""
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRAG = ROOT / "data" / "p7"
OUT = ROOT / "data" / "p7.yaml"

SANGAHA_ORDER = ["akusala", "missaka", "bodhipakkhiya", "sabba"]

HEADER = """\
# ปริจเฉทที่ ๗ สมุจจยสังคหะ -- dhamma-set <-> ปรมัตถ์ data for the /julator/p7 tool.
#
# GENERATED by scripts/assemble_p7.py from the per-สังคหะ fragments in data/p7/.
# NEVER hand-edit this file -- edit data/p7/<sangaha>.yaml and re-run the script.
#
# All 4 สังคหะ (akusala 9 sets, missaka 7, bodhipakkhiya 7, sabba 5 = 28
# dhamma-sets, ~198 named members) are verified against
# reference/02-ปริจเฉทที่7-สมุจจยสังคหะ.md, one สังคหะ per subagent (2026-08-30).
# Per-set verification notes: docs/p7-verification/<sangaha>.md.
#
# scripts/build_data.py checks every `ongkhatham` id against data/paramattha.yaml
# and every `expect` == len(members), then emits the reverse index
# (ปรมัตถ์ id -> [{sangaha, set, member}]).
#
# ---- shape ----
# sangahas:
#   - id: akusala
#     thai: อกุศลสังคหะ
#     gatha / gatha_source / source / note        # optional สังคหะ-level context
#     sets:
#       - id: asava
#         thai: อาสวะ
#         count_label: "๔"      # traditional count, for display (Thai numerals)
#         gatha / source / note  # optional; `note` holds deferred sub-classifications
#         expect: 4              # build_data.py checks len(members) == expect
#         members:
#           - id: kamasava
#             thai: กามาสวะ
#             ongkhatham: [lobha]   # paramattha.yaml id(s) this member resolves to
#             note: "โลภเจตสิก ที่ใน โลภมูลจิต ๘"
"""


def main():
    sangahas = []
    for sid in SANGAHA_ORDER:
        d = yaml.safe_load((FRAG / f"{sid}.yaml").read_text(encoding="utf-8"))
        d.pop("count_label", None)  # stray key in one fragment; meaningless at สังคหะ level
        ordered = {"id": d["id"], "thai": d["thai"]}
        for k in ("gatha", "gatha_source", "source", "note"):
            if k in d:
                ordered[k] = d[k]
        ordered["sets"] = d["sets"]
        sangahas.append(ordered)

    with OUT.open("w", encoding="utf-8") as f:
        f.write(HEADER + "\n")
        yaml.safe_dump({"sangahas": sangahas}, f, allow_unicode=True, sort_keys=False,
                       width=1000, default_flow_style=False)

    n_sets = sum(len(s["sets"]) for s in sangahas)
    n_mem = sum(len(st["members"]) for s in sangahas for st in s["sets"])
    print(f"wrote {OUT} ({len(sangahas)} สังคหะ, {n_sets} sets, {n_mem} members)")


if __name__ == "__main__":
    main()
